version: "3.9"
services:
  app:
    image: my-node-app
    build:
      context: .
      dockerfile: Dockerfile-alpine
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000

